Defaults:
  ConvertFrom: ""
  ShouldWithdrawCommandExist: true
  WithdrawMininum: 20.0
  ShouldKeepLastPlayerAsDamager: true
  HowLongShouldPlayerBeLastDamager: 20
  ShouldDamageScaleWithHealth: false
  MaxHeartAmount: 60.0
  StartHeartAmount: 20.0
  ZeroedRespawnAmount: 15.0
  LoseHeartsOnNonPlayerDeath: false
  HeartsLostOnDeath: 2.0
  HeartsGainedOnKill: 2.0
  HeartsZeroedAmount: 0.0
  CommandsAfterDeath: []
  CommandsAfterKill: []
  CommandsAfterZeroing:
  - "tempban %player% 7d Try again later"
  DisabledWorlds: []
MySQL: 
  Enabled: false
  AutoReconnect: false
  Host: 127.0.0.1
  Database: database
  Username: LifeSteal
  Password: '12345'
  Port: 3306
TAB:
  Enabled: false
  Colors:
    - "100:&a"
    - "10:&e"
    - "5:&c"
HeartCanaster:
  AmountGive: 2.0
  Item:
    Material: PLAYER_HEAD
    CustomModelData: 0
    DisplayName: "Heart Canaster"
    Lore:
    - "Right click this item to get a heart"
  RecipeEnabled: true
  Recipe:
    Type: Shaped
    Contents:
    - "*:DIAMOND"
    - "-:GOLDEN_APPLE"
    Shape:
    - "***"
    - "*-*"
    - "***"