name: LifeStealSMP
main: com.gamerduck.LifeStealMain
version: ${project.version}
description: lifestealsmp plugin thingy
api-version: 1.18
softdepend: [PlaceholderAPI]
commands:
  lifesteal:
    description: main command
  withdraw:
    description: main command