name: LifeStealSMP
main: com.gamerduck.LifeStealMain
version: 0.1.1-SNAPSHOT
description: lifestealsmp plugin thingy
api-version: 1.18
commands:
  lifesteal:
    description: main command
  withdraw:
    description: main command